### ISSUE TITLE
Updates regarding Driveworks 5.0.10

### ISSUE THREAD

**Issue by SeongHyunBae** [DavidTorresOcana/ros_gmsl_driver#1]
Hi, after updating Driveworks to the latest version (5.0.10) there are numerous errors regarding the dwImageFormat. Could you provide any link, method or code to fix this error? 
Thanks in advance

error log : 
{main.cpp:89:5: error: ‘dwImageFormatConverterHandle_t’ does not name a type dwImageFormatConverterHandle_t yuv2rgba}
{main.cpp: In function ‘void threadCameraPipeline(Camera*, uint32_t, dwContextHandle_t, WindowBase*)’}

**Comment by DavidTorresOcana** [comment]
Hello

This due to using latest Driveworks release when the current driver is only supports 5.0.5.
I am unable to do the migration to 5.0.10 at the moment, so I would suggest (and ask) for you to try to do the required modifications.

It must be that they changed the Image Converter definitions. Please visit Driveworks documentation in DrivePX2 /usr/local/driveworks/doc/nvdwx_html/group__converter__group.html

There you will find the Image Converter definitions.
A good idea too is to see an example, so you can visit /usr/local/driveworks/samples/src/sensors/camera_gmsl/main.cpp Line 340 (aprox) and try to modify https://github.com/DavidTorresOcana/ros_gmsl_driver/blob/master/src/main.cpp#L89 accordingly 

I encourage you to branch and do a merge request if you manage to do it :)

Regards

**Comment by jokla** [comment]
Hi @SeongHyunBae,

Have you managed to update the ROS driver?

Thanks!

**Comment by SeongHyunBae** [comment]
Sorry, I have no time to do that. So I'm using old version sdk

**Comment by DavidTorresOcana** [comment]
Hello

Now this is solved on #3 thanks to @xbasti07x
